# generated asset index
# format: name<TAB>bytes<TAB>sha256
# this file is regenerated by the build; edits are lost.
# folder	2001/fa01/0401/ed01/5a01/f901/3b01/c201/c601/ef01/e701/2a01/6c01/fe01/1c01/7e01/3301/3d17
