# generated asset index
# format: name<TAB>bytes<TAB>sha256
# this file is regenerated by the build; edits are lost.
# folder	8507/c107/af07/ab07/8e07/1907/2907/ec07/0007/c407/4207/ce07/4407/5107/3907/bf07/e604
