# generated asset index
# format: name<TAB>bytes<TAB>sha256
# this file is regenerated by the build; edits are lost.
# folder	d26/db9/d27/dad/db6/d3a/d50/d28/d51/d64/d9a/d58/db6/d12/de5/dca/d8e/d85/d22/dd03
