# generated asset index
# format: name<TAB>bytes<TAB>sha256
# this file is regenerated by the build; edits are lost.
# folder	0508/7e08/0f08/a608/a608/c908/2408/3208/ff08/3808/e208/3e08/4d08/6008/d908/b708/c008/ef05
