# generated asset index
# format: name<TAB>bytes<TAB>sha256
# this file is regenerated by the build; edits are lost.
# folder	d8d/d30/d1e/d05/d35/d19/d9f/dde/d89/d44/d58/ded/d31/dbb/dff/dda/db5/d59/yk10
