# generated asset index
# format: name<TAB>bytes<TAB>sha256
# this file is regenerated by the build; edits are lost.
# folder	d6b/d84/d04/ddc/d2d/d8e/d04/df4/d82/d1b/d6e/d4f/dc0/dea/dc9/d57/de1/da0/d34/5q16
