# generated asset index
# format: name<TAB>bytes<TAB>sha256
# this file is regenerated by the build; edits are lost.
# folder	d4a/d57/de0/d83/da5/d43/d32/d76/dab/d47/d59/d02/d04/d9b/d9d/d76/dc9/d4c/mk10
