# generated asset index
# format: name<TAB>bytes<TAB>sha256
# this file is regenerated by the build; edits are lost.
# folder	8f05/6c05/a205/0b05/1405/9005/7305/7f05/cc05/2905/6105/ca05/5805/bf05/4c05/f005/b205/4205/7119
