# generated asset index
# format: name<TAB>bytes<TAB>sha256
# this file is regenerated by the build; edits are lost.
# folder	d46/dce/dc6/d7c/da9/d17/d2e/d35/d22/d74/d5f/d26/dd5/dbe/df6/dba/d85/dd4/d02/2r17
