# generated asset index
# format: name<TAB>bytes<TAB>sha256
# this file is regenerated by the build; edits are lost.
# folder	dcd/d0e/d8c/d37/daf/d7a/de5/d7d/dd5/d32/dff/ddd/d99/d7e/d6b/d4e/da0/d41/d00/2o14
