# generated asset index
# format: name<TAB>bytes<TAB>sha256
# this file is regenerated by the build; edits are lost.
# folder	d8d/d92/dab/dd0/d12/dea/df5/dca/d0a/d75/d8a/d0c/d54/d0c/da9/d9b/dad/dc6/ee04
