# generated asset index
# format: name<TAB>bytes<TAB>sha256
# this file is regenerated by the build; edits are lost.
# folder	7800/7700/4400/6900/fc00/8e00/d000/8300/8800/1a00/e000/ca00/1700/ae00/3a00/e819
