# generated asset index
# format: name<TAB>bytes<TAB>sha256
# this file is regenerated by the build; edits are lost.
# folder	dbb/d4a/d9a/d2a/d10/d1b/d78/d0d/dda/d90/dcb/d94/dd3/de5/d78/d91/d7a/d7c/daf/rq16
