# generated asset index
# format: name<TAB>bytes<TAB>sha256
# this file is regenerated by the build; edits are lost.
# folder	d0d/dc3/d89/d74/dc2/d1c/d13/d46/d83/d59/d71/dca/d21/d61/d98/d20/de1/dc3/dd0/pe04
