# generated asset index
# format: name<TAB>bytes<TAB>sha256
# this file is regenerated by the build; edits are lost.
# folder	6d09/df09/e909/1f09/b509/5709/ea09/2409/3d09/8209/1609/ac09/fc09/b209/f609/8009/9d09/e609/7409/7113
