# generated asset index
# format: name<TAB>bytes<TAB>sha256
# this file is regenerated by the build; edits are lost.
# folder	ac11/4711/7a11/0f11/ae11/b011/d011/ed11/5e11/f211/6d11/4211/1e11/eb11/3210
